### ISSUE TITLE
Server-Wide Statistics Displays "NaN Seconds"

### ISSUE THREAD

**Issue by edwardscaleb9** [aunefyren/plex-wrapped#5]
Platform: Docker behind Nginx reverse proxy (issue is present when bypassing reverse proxy as well)

Expected behavior: Server-wide statistics area should be displaying the total number of seconds all users combined spent watching content.

Actual behavior: Server-wide statistics area is displaying "That is NaN seconds of content!"

Are there any logs I can provide? I checked the browser console but all I see is:
`my.domain/:1 Error handling response: TypeError: Cannot read properties of undefined (reading 'takeRecords')
    at Function.e.closeListeners (chrome-extension://jkgeppojddflfhbfhjgapbcdnabegmdg/content-script.js:1:5858)
    at chrome-extension://jkgeppojddflfhbfhjgapbcdnabegmdg/content-script.js:1:3858`

**Comment by aunefyren** [comment]
Weird. Does every other statistic load properly and only server-wide watch time is NaN? 

Is server-wide watch time for every media-type NaN or is only the combined watch time for movies, shows and music NaN?

**Comment by edwardscaleb9** [comment]
All other statistics work properly. The different media types work correctly, it's just the combined time in seconds that is showing as NaN.

![image](https://user-images.githubusercontent.com/10451532/144434309-3b79d62c-b02c-47af-a8f1-cc1f80a00b96.png)
